service: h8pdf

custom:
  defaultStage: dev # default stage to deploy to

  myStage: ${opt:stage, self:custom.defaultStage} # deploy to the stage that is given via a CLI param with fallback to the default stage

provider:
  name: aws
  runtime: nodejs8.10

package:
  exclude:
    - test/**
    - lib/**.test.**
    - .idea/**

functions:
  pdf-getFields:
    handler: pdf.getFields

